export const totalPrice = $('#total');
export const paymentButton = $('button=Pay with Card');
export const iframe = $('iframe[name="stripe_checkout_app"]');
export const email = $("//input[@placeholder='Email']");
export const cardNumber = $("//input[@placeholder='Card number']");
export const expiryDate = $("//input[@placeholder='MM / YY']");
export const cvc = $("//input[@placeholder='CVC']");
export const billingZip = $("//input[@placeholder='ZIP Code']");
export const submitButton = $('#submitButton');
export const successMessage = $('h2');